### ISSUE TITLE
Migrate to Google Cloud

### ISSUE THREAD

**Issue by JelNiSlaw** [AI-AI-Boyzz/medrzec-ai#27]
- [x] move api
- [ ] move slack-bot
- [x] setup SSL
- [x] enable build cache

**Comment by JelNiSlaw** [comment]
I have found the cause and reported the issue to hop.io

**Comment by remote-how-iwo** [comment]
Renamed the issue from "fixing Hop" to moving to GCP

**Comment by JelNiSlaw** [comment]
slack bot issue moved to https://github.com/AI-AI-Boyzz/slack-bot/issues/2
