### ISSUE TITLE
Fix "Failed to fetch" bug with web chat

### ISSUE THREAD

**Issue by remote-how-iwo** [AI-AI-Boyzz/medrzec-ai#43]
![Image](https://user-images.githubusercontent.com/107128351/251157322-8f138bff-bf4f-4de0-8621-62cc6b212682.png)
![Image](https://user-images.githubusercontent.com/107128351/251157321-1fdf13da-bafd-4705-a35b-f07bfe28c79f.png)

**Comment by JelNiSlaw** [comment]
fixed in 0bf78905a5581c96a86a5ca5f59b1ca2892216b0
