### ISSUE TITLE
Find a way to get user's answers to a list of questions

### ISSUE THREAD

**Issue by JelNiSlaw** [AI-AI-Boyzz/medrzec-ai#5]
The goal of this feature, use similarity search to answer the questions for the user instead of throwing them directly at the user.

**Comment by remote-how-iwo** [comment]
@JelNiSlaw this is the questionnaire, make sure to take into consideration the **importance** https://docs.google.com/spreadsheets/d/1_TLqwvusKz7APOLwf2SlNJScXGEmsZTKORC48FTI8ag/edit?usp=sharing
