### ISSUE TITLE
Optimize current Agent flow prompts - save responses and generate summary after each stage (for the report)

### ISSUE THREAD

**Issue by remote-how-iwo** [AI-AI-Boyzz/medrzec-ai#97]

**Comment by remote-how-iwo** [comment]
@JelNiSlaw as discussed, current prompts setup will be updated based on this convo: https://remote-how-workspace.slack.com/archives/C05BNSC4XQW/p1689852136900329

**Comment by JelNiSlaw** [comment]
updated all prompts
